data:
  train_data_path: /scratch/hs5580/ddrl/overcooked/data/2020_hh_trials.csv
  val_data_path: null
  val_ratio: 0.1
  max_samples: 1000
model:
  type: grid
  state_embed_dim: 128
  action_embed_dim: 4
  num_actions: 6
  dynamics_hidden_dim: 256
  reward_hidden_dim: 64
  grid_height: 5
  grid_width: 13
training:
  output_dir: /scratch/hs5580/ddrl/overcooked/models/grid_model
  batch_size: 64
  learning_rate: 1e-4
  dynamics_epochs: 2
  reward_epochs: 2
  log_interval: 5
  num_workers: 4
  device: auto
testing:
  test_data_path: null
  num_samples: 100
