seed: 101
data:
  train_data_path: /scratch/hs5580/ddrl/overcooked/data/2020_hh_trials.csv
  val_data_path: null
  val_ratio: 0.1
  test_ratio: 0.1
  max_samples: null
model:
  type: grid
  state_embed_dim: 128
  action_embed_dim: 4
  num_actions: 6
  dynamics_hidden_dim: 256
  reward_hidden_dim: 64
  grid_height: 5
  grid_width: 13
training:
  output_dir: ./models/grid_default
  batch_size: 64
  learning_rate: 0.0001
  dynamics_epochs: 200
  reward_epochs: 100
  log_interval: 50
  num_workers: 8
  device: auto
  max_iterations: 1000
  max_steps: 500
testing:
  test_data_path: null
  num_samples: 100
  planning_horizon: 400
  planning_samples: 100
wandb:
  use_wandb: true
  project: rl-overcooked
  name: grid_default
  entity: harshsutariya1179
