# Default configuration file for grid-based PLDM models
# This configuration uses the grid-based state representation

# General settings
seed: 101  # Random seed for reproducibility

# Workflow control
workflow:
  run_training: true   # Enable training phase
  run_probing: true    # Enable probing phase  
  run_planning: true   # Enable planning phase

# Data parameters
data:
  train_data_path: "./data/2020_hh_trials.csv"
  val_data_path: null  # Will use split from train data
  test_data_path: null  # Will use split from train data
  val_ratio: 0.1
  test_ratio: 0.1
  grid_size: 5

# Model parameters
model:
  type: "grid"
  encoder_type: "cnn"
  # grid encoder params
  grid_dims:
    H: 5
    W: 5
  in_channels: 26
  num_objects: 17
  hidden_channels: [16, 32, 64]
  fc_dims: [256, 128]
  # reward predictor params
  reward_hidden_dims: [128, 64, 32]
  reward_activation: "relu"
  # dynamics predictor params
  dynamics_hidden_dims: [128, 64, 32]
  dynamics_activation: "relu"
  # general params
  activation: "relu"
  use_layer_norm: false
  device: "cuda"

# Training parameters
training:
  batch_size: 128
  dynamics_epochs: 10
  reward_epochs: 5
  learning_rate: 0.001
  optimizer: "adam"
  weight_decay: 0.00001
  scheduler: "plateau"
  scheduler_patience: 10
  scheduler_factor: 0.5
  scheduler_min_lr: 0.000001
  max_norm: 1.0
  use_layer_norm: false
  seed: 42
  log_interval: 10
  num_workers: 4

# Testing parameters
testing:
  batch_size: 128
  use_val_data: false
  use_test_data: true
  num_samples: 100
  planning_horizon: 5
  planning_samples: 100

# WandB parameters
wandb:
  project: "pldm-overcooked"
  name: base
  entity: harshsutariya1179
  use_wandb: true  # Disabling WandB due to SSL certificate issues
  watch_model: true
  save_model: true
  
probing:
  # Probing targets
  targets: ["agent_pos"]
  probe_dynamics: true
  probe_reward: false
  
  # Model parameters
  hidden_dims: [128, 64]
  activation: "relu"
  
  # Training parameters
  batch_size: 64
  epochs: 20
  lr: 0.001
  val_ratio: 0.1
  test_ratio: 0.1
  
  # Visualization settings
  visualize: true
  max_vis_samples: 10