# Default configuration file for grid-based PLDM models
# This configuration uses the grid-based state representation

# General settings
seed: 101  # Random seed for reproducibility

# Data parameters
data:
  train_data_path: "/scratch/hs5580/ddrl/overcooked/data/2020_hh_trials.csv"  # Path to CSV dataset
  val_data_path: null                            # If null, will use a split of train data
  val_ratio: 0.1                                 # Ratio of train data to use for validation
  test_ratio: 0.1                                # Ratio of train data to use for testing
  max_samples: null                              # Maximum number of samples to use (for testing)

# Model parameters
model:
  type: "grid"                                   # 'grid' or 'vector'
  state_embed_dim: 128                           # Dimension of state embedding
  action_embed_dim: 4                            # Dimension of action embedding
  num_actions: 6                                 # Number of possible actions
  dynamics_hidden_dim: 256                       # Hidden dimension for dynamics predictor
  reward_hidden_dim: 64                          # Hidden dimension for reward predictor
  grid_height: 5                                 # Height of the grid
  grid_width: 13                                 # Width of the grid

# Training parameters
training:
  output_dir: ./models/grid_default
  batch_size: 64
  learning_rate: 0.0001
  dynamics_epochs: 200
  reward_epochs: 100
  log_interval: 50
  num_workers: 8
  device: auto
  max_iterations: 1000
  max_steps: 500

# Testing parameters
testing:
  test_data_path: null
  num_samples: 100
  planning_horizon: 400
  planning_samples: 100

# WandB parameters
wandb:
  use_wandb: true                                # Whether to use WandB logging
  project: rl-overcooked
  name: grid_default
  entity: harshsutariya1179