# Configuration file for training-only workflow
# This configuration only runs the training phase, skipping probing and planning

# General settings
seed: 42  # Random seed for reproducibility

# Workflow control
workflow:
  run_training: true   # Enable training phase
  run_probing: false   # Skip probing phase  
  run_planning: false  # Skip planning phase

# Data parameters
data:
  train_data_path: "/scratch/hs5580/ddrl/overcooked/data/2020_hh_trials.csv"
  val_data_path: null
  val_ratio: 0.1
  test_ratio: 0.1
  max_samples: null  # Use all data

# Model parameters
model:
  type: "grid"
  state_embed_dim: 128
  action_embed_dim: 4
  num_actions: 6
  dynamics_hidden_dim: 256
  reward_hidden_dim: 64
  grid_height: 5
  grid_width: 13

# Training parameters
training:
  output_dir: "/scratch/hs5580/ddrl/overcooked/models/grid_train_only"  # New directory for training-only models
  batch_size: 64
  learning_rate: 1e-4
  dynamics_epochs: 200  # More epochs for thorough training
  reward_epochs: 100
  log_interval: 20
  num_workers: 8
  device: "auto"

# WandB parameters
wandb:
  use_wandb: true
  project: "pldm-training"
  name: "grid_train_only"
  entity: null 