data:
  train_data_path: /scratch/hs5580/ddrl/overcooked/data/2020_hh_trials.csv
  val_data_path: null
  val_ratio: 0.1
  max_samples: null
model:
  type: grid
  state_embed_dim: 128
  action_embed_dim: 4
  num_actions: 6
  dynamics_hidden_dim: 256
  reward_hidden_dim: 64
  grid_height: 5
  grid_width: 13
training:
  output_dir: /scratch/hs5580/ddrl/overcooked/models/vicreg_grid
  batch_size: 64
  learning_rate: 0.0001
  dynamics_epochs: 200
  reward_epochs: 100
  log_interval: 50
  num_workers: 8
  device: auto
  use_vicreg: true
vicreg:
  sim_coeff: 25.0
  std_coeff: 25.0
  cov_coeff: 1.0
  std_margin: 1.0
  mse_coeff: 1.0
  projection_dim: 256
  use_projector: true
testing:
  test_data_path: null
  num_samples: 100
  planning_horizon: 100
  planning_samples: 100
wandb:
  project: rl-overcooked-vicreg
  name: vicreg_grid_model
  entity: harshsutariya1179
