seed: 101
workflow:
  run_training: true
  run_probing: true
  run_planning: true
data:
  train_data_path: ./data/2020_hh_trials.csv
  val_data_path: null
  val_ratio: 0.1
  test_ratio: 0.1
  max_samples: null
  test_data_path: null
  grid_size: 5
model:
  type: grid
  state_embed_dim: 128
  action_embed_dim: 4
  num_actions: 6
  dynamics_hidden_dim: 256
  reward_hidden_dim: 64
  grid_height: 5
  grid_width: 13
  encoder_type: cnn
  grid_dims:
    H: 5
    W: 5
  in_channels: 26
  num_objects: 17
  hidden_channels:
  - 16
  - 32
  - 64
  fc_dims:
  - 256
  - 128
  reward_hidden_dims:
  - 128
  - 64
  - 32
  reward_activation: relu
  dynamics_hidden_dims:
  - 128
  - 64
  - 32
  dynamics_activation: relu
  activation: relu
  use_layer_norm: false
  device: cuda
training:
  output_dir: ./models
  batch_size: 128
  learning_rate: 0.001
  dynamics_epochs: 10
  reward_epochs: 5
  log_interval: 10
  num_workers: 4
  device: auto
  optimizer: adam
  weight_decay: 1.0e-05
  scheduler: plateau
  scheduler_patience: 10
  scheduler_factor: 0.5
  scheduler_min_lr: 1.0e-06
  max_norm: 1.0
  use_layer_norm: false
  seed: 42
testing:
  test_data_path: null
  num_samples: 100
  planning_horizon: 5
  planning_samples: 100
  batch_size: 128
  use_val_data: false
  use_test_data: true
wandb:
  use_wandb: true
  project: pldm-overcooked
  name: base
  entity: harshsutariya1179
  watch_model: true
  save_model: true
probing:
  targets:
  - state
  - reward
  - agent_pos
  probe_dynamics: true
  probe_reward: true
  hidden_dims:
  - 128
  - 64
  activation: relu
  batch_size: 64
  epochs: 20
  lr: 0.001
  val_ratio: 0.1
  test_ratio: 0.1
  visualize: true
  max_vis_samples: 10
